services:
  - type: web
    name: zoom-automation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0